# Generated by Django 3.0.3 on 2020-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_book_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
