# Generated by Django 3.0.3 on 2020-03-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bookapproved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookApproved',
        ),
    ]
